export const API_PREFIX = process.env.VUE_APP_API_URI
export const PAGE_ONE_SEARCH = (page = 0, items = 15) => `pageNumber=${page}&itemsPerPage=${items}`
export const MEDIA_TYPE = (type = 'video') => API_PREFIX + "/media/list" + `/${type}`
export const CODE_TYPE_LIST = (type = 'promo') => {
  if (type !== "promo")
    return API_PREFIX + "/aia-codes/list"
  return API_PREFIX + "/promo-codes"
}
export const CODE_TYPE_URL = (type = 'promo') => {
  if (type !== "promo")
    return API_PREFIX + "/aia-codes"
  return API_PREFIX + "/promo-codes"
}
export const REFRESH_TOKEN = API_PREFIX + "/refresh-token"
export const LOGIN = API_PREFIX + "/auth/admin-login"
export const LOGOUT = API_PREFIX + "/logout"
export const PROFILE = API_PREFIX + "/profile/admin"
export const CHANGE_PASSWORD = API_PREFIX + "/user/change-password"
export const PROFILE_INFO = API_PREFIX + "/profile/update-info"
export const LIST_USERS = API_PREFIX + "/user/list"
export const USER = API_PREFIX + "/user"
export const PROFILE_USER = API_PREFIX + "/profile"
export const MEMBERSHIP = API_PREFIX + "/membership"
export const MEMBERSHIP_TYPE = API_PREFIX + "/membership-type"
export const MEDIA = API_PREFIX + "/media"
export const PAYMENT = API_PREFIX + "/payment"
export const PAYMENT_LIST = API_PREFIX + "/payment/list"
export const RECIPE_LIST = API_PREFIX + "/recipes/list"
export const RECIPE_MEAL_LIST = API_PREFIX + "/recipes-meal/list"
export const RECIPE_TYPE_LIST = API_PREFIX + "/recipes-type/list"
export const RECIPE_CATEGORY_LIST = API_PREFIX + "/recipes-category/list"
export const RECIPE_DIETARY_LIST = API_PREFIX + "/recipes-dietary/list"
export const RECIPE_TAG_LIST = API_PREFIX + "/recipes-tags/list"
export const INGREDIENT_LIST = API_PREFIX + "/ingredients/list"
export const RECIPE = API_PREFIX + "/recipes"
export const RECIPE_REFRESH = API_PREFIX + "/recipes/refresh-view"
export const TRACKING_TOPIC = API_PREFIX + "/track-topic"
export const TRACKING_ANSWER = API_PREFIX + "/track-answer"
export const SURVEY = API_PREFIX + "/survey"
export const SURVEY_ANSWER = API_PREFIX + "/survey-answer/list"
export const PROMO_CODE = API_PREFIX + "/promo-codes"
export const AIA_CODE = API_PREFIX + "/aia-codes"
export const MEDIA_TOPIC = API_PREFIX + "/media-topic"
export const MEDIA_SERIES = API_PREFIX + "/media-series"
export const MEDIA_TAGS = API_PREFIX + "/media-tag"
export const MEDIA_CATEGORY = API_PREFIX + "/media-category"
export const INGREDIENTS = API_PREFIX + "/ingredients"
export const INGREDIENTS_CATEGORY = API_PREFIX + "/ingredients-category"
export const DIETARY = API_PREFIX + "/dietary"
export const RECIPE_MEAL = API_PREFIX + "/recipes-meal"
export const RECIPE_TAGS = API_PREFIX + "/recipes-tags"
export const RECIPE_CATEGORY = API_PREFIX + "/recipes-category"
export const RECIPE_DIETARY = API_PREFIX + "/recipes-dietary"
export const RECIPE_TYPE = API_PREFIX + "/recipes-type"
export const MEAL_PLAN = API_PREFIX + "/meal-plan"
export const MENU_FOOD = API_PREFIX + "/menu-food"
export const IMPORT_DATABASE_EXCEL = API_PREFIX + "/action-data/import-excel"
export const EXPORT_DATABASE_EXCEL = API_PREFIX + "/action-data/export-excel"
export const COLLECTIONS = API_PREFIX + "/action-data/collections"
export const SYSTEM = API_PREFIX + "/system"
export const CAMPAIGN = API_PREFIX + "/campaign"
export const MAIL_CHIMP = API_PREFIX + "/mail-chimp"
